services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - hotel-network

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./src/main/resources/db/migration/V1__create_searches_table.sql:/container-entrypoint-initdb.d/V1__create_searches_table.sql
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/1521" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    networks:
      - hotel-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-availability
    depends_on:
      kafka:
        condition: service_healthy
      oracle:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: "60000"
      SPRING_DATASOURCE_HIKARI_INITIALIZATION-FAIL-TIMEOUT: "-1"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge

volumes:
  oracle-data: