spring:
  application:
    name: hotel-availability

  # Virtual threads — Java 21 Project Loom
  threads:
    virtual:
      enabled: true

  # Oracle XE datasource
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: -1

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: hotel-availability-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.challenge.hotel.infrastructure.output.kafka"
        spring.json.value.default.type: "com.challenge.hotel.infrastructure.output.kafka.SearchMessage"

# Springdoc OpenAPI / Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

# Server
server:
  port: 8080
